### PR TITLE
Give --top-level a more useful default so it won't need to be specifi…

### PR DESCRIPTION
**Pull request by rotx-maxim**
…ed most of the time

### CODE REVIEW

**Review by MaximGorkem — APPROVED** [review]
looking good

**Review by MaximGorkem — APPROVED** [review]
looking good

**Review by vicloginov — APPROVED** [review]
Looks good

**Review by MaximGorkem — APPROVED** [review]

**Review by aniktash — COMMENTED** [review]
sounds good

**Review by ermanok — APPROVED** [review]
looks ok.

**Pull request merged**
