### PR TITLE
Fix shift calculation by considering biases

### PR DESCRIPTION
**Pull request by MaximGorkem**
Biases are used to be taken into consideration while calculating the factor but not in writing the out_shift. This commit fixes this.

### CODE REVIEW

**Review by rotx-maxim — APPROVED** [review]

**Review by ermanok — APPROVED** [review]
That's OK.

**Comment by MaximGorkem** [comment]
Added another changed file to this PR.

**Review by rotx-maxim — COMMENTED** [review]
Verify how this change affects cifar100_qat_mixed

**Comment by MaximGorkem** [comment]
Verification done, the new version works in both cifar100_qat_mixed and unet v7 with no accuracy difference with their QAT versions.

**Review by ermanok — APPROVED** [review]
Looks good.

**Pull request merged**
